variable "project" {}
variable "tags" {}
variable "environment" {}
variable "certificate_arn" {}
variable "bucket_domain_name" {}
variable "website_endpoint" {}
variable "cloudfront_access_identity_path" {}
variable "lambda_edge_cloudfront_iam_role_arn" {}
variable "tile_cache_app_url" {}