version: "3.5"

services:
  app:
    build:
      context: .
      args:
        - ENV=dev
    container_name: tile-cache_dev
    restart: on-failure
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./app:/app/app
    networks:
      - gfw-data-api
    environment:
      - DB_HOST_RO=database
      - DATABASE_RO=geostore
      - DB_USER_RO=gfw_readonly
      - DB_PASSWORD_RO=readonly  # pragma: allowlist secret
      - DB_PORT_RO=5432
      - AWS_DEFAULT_PROFILE=gfw-dev
      - LOG_LEVEL=debug
      - ENV=dev
    ports:
      - 8088:80
    entrypoint: wait_for_postgres.sh /start-reload.sh

networks:
  gfw-data-api:
    name: gfw-data-api_dev_default