version: "3.5"

services:
  app:
    build:
      context: .
      args:
        - ENV=dev
    container_name: tile-cache_dev
    restart: on-failure
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./app:/app/app
    networks:
      - gfw-data-api
    environment:
      - DB_HOST_RO=host.docker.internal
      - DATABASE_RO=${GFW_DB_NAME}
      - DB_USER_RO=${GFW_DB_USER_RO}
      - DB_PASSWORD_RO=${GFW_DB_PASSWORD_RO}
      - DB_PORT_RO=5432
      - AWS_DEFAULT_PROFILE=${AWS_PROFILE}
      - DATA_LAKE_BUCKET=${DATA_LAKE_BUCKET}
      - LOG_LEVEL=debug
      - RASTER_TILER_LAMBDA_NAME=test
      - ENV=dev
      - PLANET_API_KEY
      - AWS_REQUEST_PAYER=requester
    ports:
      - 8088:80
    entrypoint: wait_for_postgres.sh /start-reload.sh

networks:
  gfw-data-api:
    name: gfw-data-api_dev_default