version: "3"

services:
  app:
    build:
      context: .
      args:
        - ENV=production
    container_name: tile-cache-prod
    restart: on-failure
    volumes:
      - $HOME/.aws:/root/.aws:ro
      - ./app:/app/app
    environment:
      - DB_HOST_RO=database
      - DATABASE_RO=geostore
      - DB_USER_RO=gfw_readonly
      - DB_PASSWORD_RO=readonly  # pragma: allowlist secret
      - DB_PORT_RO=5432
      - AWS_DEFAULT_PROFILE=gfw-dev
      - LOG_LEVEL=debug
      - ENV=production
    ports:
      - 8088:80
    entrypoint: wait_for_postgres.sh /app/start.sh
    depends_on:
      - database

  database:
    container_name: gfw-data-api-database
    image: postgis/postgis:12-2.5-alpine
    restart: on-failure
    ports:
      - 54320:5432
    environment:
      - POSTGRES_DB=geostore
      - POSTGRES_USER=gfw
      - POSTGRES_PASSWORD=postgres  # pragma: allowlist secret
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
