[project]
name = "gfw-tile-cache"
version = "0.1.0"
description = "Add your description here"
requires-python = "~=3.11.0"
dependencies = [
    "aenum<3.0",
    "aioboto3",
    "aiobotocore",
    "aiofiles",
    "async-lru",
    "asyncpg",
    "cachetools",
    "fastapi",
    "geojson",
    "gino",
    "gino-starlette",
    "gunicorn",
    "httpx",
    "httpx-auth",
    "jinja2",
    "mercantile",
    "newrelic",
    "numpy",
    "orjson",
    "pendulum",
    "psycopg2",
    "pydantic",
    "pydantic-settings",
    "pyproj",
    "rasterio==1.4.3",
    "shapely",
    "sqlalchemy<1.4",
    "starlette",
    "titiler",
    "uvicorn[standard]",
]

[dependency-groups]
dev = [
    "boto3",
    "localstack-utils",
    "pillow>=11.3.0",
    "pre-commit",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-dotenv",
]
