#!/bin/bash

export COMPOSE_DOCKER_CLI_BUILD="1" DOCKER_BUILDKIT="1"

set -e

docker compose -f terraform/docker/docker-compose.yml build
docker compose -f terraform/docker/docker-compose.yml run --entrypoint delete_workspace --rm  terraform "$@"