#!/bin/bash

set -e

# Default values
POSITIONAL=()
BUILD=true
COMPOSE_FILE="docker-compose.dev.yml"

# extracting cmd line arguments
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
      --no_build)
      BUILD=false
      shift # past argument
      ;;
      --local_data_api)
      COMPOSE_FILE="docker-compose-local-data-api.dev.yml"
      shift # past argument
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ "${BUILD}" = true ]; then
  docker-compose -f "${COMPOSE_FILE}" up --abort-on-container-exit --remove-orphans --build
else
  docker-compose -f "${COMPOSE_FILE}" up --abort-on-container-exit --remove-orphans
fi
