#!/bin/bash

export COMPOSE_DOCKER_CLI_BUILD="1" DOCKER_BUILDKIT="1"

set -e

GIT_SHA=$(git rev-parse HEAD)

docker compose -f terraform/docker/docker-compose.yml build
docker compose -f terraform/docker/docker-compose.yml run --rm terraform "$@" -var="git_sha=${GIT_SHA}" -w default  # force terraform to always use default branch