#!/bin/bash

set -e

docker-compose -f terraform/docker/docker-compose.yml build
docker-compose -f terraform/docker/docker-compose.yml run --rm terraform "$@" -w default  # force terraform to always use default branch