#!/usr/bin/env bash

pip install -r requirements-dev.txt
pip install -e .

detect-secrets scan > .secrets.baseline
pre-commit install

docker-compose -f docker/terraform/docker-compose.yml build
./scripts/cibuild