#!/bin/bash

set -e

PYTHON_RUNTIME="python3.10"
MERCANTILE_VERSION="1.2.1"
NUMPY_VERSION="1.26.4"
PILLOW_VERSION="9.5.0"
RASTERIO_VERSION="1.3.8"

MERCANTILE_FILENAME="${PYTHON_RUNTIME}-mercantile_${MERCANTILE_VERSION}.zip"
NUMPY_FILENAME="${PYTHON_RUNTIME}-numpy_${NUMPY_VERSION}.zip"
PILLOW_FILENAME="${PYTHON_RUNTIME}-pillow_${PILLOW_VERSION}.zip"
RASTERIO_FILENAME="${PYTHON_RUNTIME}-rasterio_${RASTERIO_VERSION}.zip"

# Default values
POSITIONAL=()
BUILD=true
# extracting cmd line arguments
while [[ $# -gt 0 ]]
do
  key="$1"

  case $key in
      --no_build)
      BUILD=false
      shift # past argument
      ;;
      *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

for filename in $MERCANTILE_FILENAME $PILLOW_FILENAME $RASTERIO_FILENAME; do
  if ! [ -f "tests/fixtures/${FILENAME}" ]; then
      aws s3 cp s3://gfw-pipelines-dev/lambda_layers/${filename} tests/fixtures/${filename}
  fi
done

if [ "${BUILD}" = true ]; then
  docker compose -f docker-compose.test.yml --project-name gfw-tile-cache_test build app
fi

set +e
docker compose -f docker-compose.test.yml --project-name gfw-tile-cache_test run --rm app tests/"$@" -vv
exit_code=$?
docker compose -f docker-compose.test.yml --project-name gfw-tile-cache_test down --remove-orphans
rm -rf tests/terraform/terraform.tfstate* \
       tests/terraform/.terraform.lock.hcl \
       tests/terraform/.terraform/modules/modules.json
exit $exit_code
