name: Plan terraform changes for base branch

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Plan production
      if: github.base_ref == 'production'
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_REGION: ${{ secrets.aws_region_production }}
      run: ./scripts/infra plan
    - name: Plan staging
      if: github.base_ref == 'staging'
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_REGION: ${{ secrets.aws_region_staging }}
      run: ./scripts/infra plan
    - name: Plan dev
      if: github.base_ref == 'dev'
      env:
        ENV: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_REGION: ${{ secrets.aws_region_dev }}
      run: ./scripts/infra plan