name: Run tests and apply terraform changes for current branch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Test with pytest
      env:
        ENV: test
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_REGION: ${{ secrets.aws_region_dev }}
        LOCALSTACK_API_KEY: ${{ secrets.localstack_api_key }}
        PLANET_API_KEY: ${{secrets.planet_api_key }}
      run: |
        ./scripts/test

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: tests/cobertura.xml

    - name: Deploy production
      if: success() && github.ref == 'refs/heads/production'
      env:
        ENV: production
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_production }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_production }}
        AWS_REGION: ${{ secrets.aws_region_production }}
      run: |
        ./scripts/infra plan
        ./scripts/infra apply

    - name: Deploy staging
      if: success() && github.ref == 'refs/heads/staging'
      env:
        ENV: staging
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_staging }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_staging }}
        AWS_REGION: ${{ secrets.aws_region_staging }}
      run: |
        ./scripts/infra plan
        ./scripts/infra apply

    - name: Deploy dev
      if: success() && github.ref == 'refs/heads/dev'
      env:
        ENV: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        AWS_REGION: ${{ secrets.aws_region_dev }}
      run: |
        ./scripts/infra plan
        ./scripts/infra apply